version: "2.2"
services:
  api:
    build:
      context: .
      dockerfile: 'Dockerfile.local'
    command: "/bin/bash -c 'yarn && yarn build &&  ENV=local yarn typeorm migration:run && yarn start:dev'"
    env_file: .env
    depends_on:
      - postgres
      - manticore
    volumes:
      - '/Users/jamestrotter/Documents/TransplexFiles/:/usr/src/local/'
      - '.:/usr/src/app'
      - 'transplex-api_deps:/usr/src/app/node_modules'
      - '/Users/jamestrotter/Documents/TransmissionDownloads:/downloads'
    ports:
      - '1337:3000'
    networks:
      - transplex-api-network
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_MULTIPLE_DATABASES=transplex,test
    volumes:
      - 'transplex-api_db:/var/lib/postgresql/data/'
      - '.db_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql'
    networks:
      - transplex-api-network
  manticore:
    hostname: manticore
    image: manticoresearch/manticore
    ports:
      - '9306:9306'
      - '9308:9308'
      - '9312:9312'
    restart: always
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - manticore_db:/var/lib/manticore
#      - ./manticore.conf:/etc/manticoresearch/manticore.conf # uncomment if you use a custom config
    networks:
      - transplex-api-network
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=transmission #optional
      - PASS=password #optional
      #- WHITELIST=iplist #optional
      #- HOST_WHITELIST=dnsnane list #optional
    volumes:
      - './transmission:/config'
      - '/Users/jamestrotter/Documents/TransmissionDownloads:/downloads'
      - './watch:/watch'
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - transplex-api-network
  plex:
    image: lscr.io/linuxserver/plex
    command: "/bin/bash -c '/plex-scripts/hama.bundle.sh'"
    container_name: plex
    ports:
      - '32400:32400'
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    volumes:
      - './plex-scripts:/plex-scripts'
      - '/Users/jamestrotter/Documents/TransplexFiles/library:/config'
      - '/Users/jamestrotter/Documents/TransplexFiles/tvseries:/tv'
      - '/Users/jamestrotter/Documents/TransplexFiles/movies:/movies'
      - '/Users/jamestrotter/Documents/TransplexFiles/anime:/anime'
    restart: unless-stopped

networks:
  transplex-api-network:
volumes:
  transplex-api_deps:
  transplex-api_db:
  manticore_db:
